on:
  push:
    tags:
      - '**'
permissions:
  contents: write
jobs:
  build_addon_software:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        id: build
        shell: pwsh
        run: |
          .\makeimage.ps1 tudelft
          $minor = [int]($Env:GITHUB_REF_NAME -split "\.")[1]
          if ($minor % 2 -eq 0) {
            Add-Content -Path $Env:GITHUB_OUTPUT -Value "draft=0"
          } else {
            Add-Content -Path $Env:GITHUB_OUTPUT -Value "draft=1"
          }
          $Env:baseurl = "https://github.com/$Env:GITHUB_REPOSITORY/releases/download/$Env:GITHUB_REF_NAME/"
          Get-Content README.md | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content README.rendered.md
          (Get-Content -Raw tudinstaller.ps1 ) -replace '%baseurl%', $Env:baseurl  | Set-Content tudinstaller.ps1
          Get-ChildItem
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            tudelft.tgz
            tudelft.tgz.hash
            tudinstaller.ps1
          body_path: README.rendered.md
          prerelease: ${{steps.build.outputs.draft == 1}}
